---
require:
  - rubocop-rake
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Lint/LiteralAsCondition:
  Enabled: false
Lint/UnreachableCode:
  Enabled: false
Layout/LineLength:
  Max: 120
Layout/ArgumentAlignment:
  Enabled: true
Metrics/ModuleLength:
  Max: 120
Metrics/ClassLength:
  Max: 120
Metrics/ParameterLists:
  Max: 10
Metrics/MethodLength:
  Max: 120
Metrics/BlockLength:
  Max: 180
Metrics/PerceivedComplexity:
  Max: 60
Metrics/CyclomaticComplexity:
  Max: 60
Metrics/AbcSize:
  Enabled: false